### PR TITLE
Switch to new Number Insight endpoints

### PR DESCRIPTION
**Pull request by cbetta**
* Add async NI Advanced method #get_advanced_async_number_insight
* Change #get_basic_number_insight and #get_standard_number_insight to use new NI endpoints

@timcraft could we get this merged and deployed? Would love to use these changes in a tutorial I'm writing.

### CODE REVIEW

**Comment by timcraft** [comment]
@cbetta I was holding off on changing the endpoints for the existing methods as it wasn't clear whether the new endpoints were backwards compatible, and therefore might be a breaking change. Do you know if the params and responses are 100% the same for `/ni/basic/json` as `/number/format/json`? Did you change them in a minor version for nexmo-node?

**Comment by cbetta** [comment]
@timcraft I didn't think there was. @tjlytle or @leggetter should now for sure.

**Comment by cbetta** [comment]
Also @timcraft it seems `public_suffix` now requires Ruby 2.0+. Seeing as Ruby 1.9.3 support has ended we can probably make a similar choice. Would be good to bump a version.

**Comment by timcraft** [comment]
@cbetta Yep I know, the error is coming from public_suffix but it's addressable 2.5.0 which dropped support for 1.9 recently. I was going to fix the gemspec for 1.9 when I release the next version, then waiting to hear about usage to see if we can drop support completely (it was EOL on 2015-02-23, but might not want to drop it immediately if people are still using it in production).

**Comment by cbetta** [comment]
@timcraft correct me if I'm wrong, but people using it in production will still be able to use the older nexmo gem right? So unless they run some massive bundle update they should not be affected.

**Comment by timcraft** [comment]
@cbetta Sure, but if they're re-bundling and haven't locked themselves to 4.3.x then it could catch someone out (assuming the endpoints aren't backwards compatible; if they are it's a non issue).

Planning to ship v4.4.0 this week anyway. When's your tutorial going out?

**Comment by timcraft** [comment]
@cbetta Merged, thanks!

**Pull request merged**
