### PR TITLE
Better errors

### PR DESCRIPTION
**Pull request by btoews**
This PR adds `#status` and `#http_status` accessors to the `Nexmo::Error` class. This should make it easier for API consumers to respond to errors.

### CODE REVIEW

**Comment by btoews** [comment]
Any thoughts on this @timcraft?

**Comment by timcraft** [comment]
@mastahyeti Definitely, sorry for the delay in reviewing!

Generally speaking I agree with being able to easily handle different HTTP responses, which is why in version 1.x.x I opted for returning the HTTP response object directly.

In v2.0.0 I changed to using the more common "return the decoded response body on success and raise exceptions on errors" for convenience. I'm of the view that developers use wrapper libraries primarily for convenience, and the gem is therefore an 80/20 solution, not designed to handle every possible option or use case.

In terms of the implementation, I don't think overloading #initialize like that is particularly good practice, and something like `attr_accessor :http_response` on the subclass would be a simpler, sufficient, and easier to maintain solution.

Is there a particular use case / error you're trying to handle, or was the motivation more of a "seems like a good idea to have this just in case" kind of thing?

**Comment by btoews** [comment]
> In terms of the implementation, I don't think overloading #initialize like that is particularly good practice, and something like attr_accessor :http_response on the subclass would be a simpler, sufficient, and easier to maintain solution.

Interesting. I feel like it is a pretty common pattern for letting exceptions carry more data. Using `attr_accessor` would be difficult because you would need to instantiate the exception, add the attribute, and then raise it.

> Is there a particular use case / error you're trying to handle, or was the motivation more of a "seems like a good idea to have this just in case" kind of thing?

At GitHub, we rely heavily on the error codes returned from our SMS providers. We use this for analytics on provider outages, determining the correct message to show to the user, etc... It's pretty ugly to have to parse an error code out of an exception message with a regex.

**Comment by timcraft** [comment]
> Using `attr_accessor` would be difficult because you would need to instantiate the exception, add the attribute, and then raise it.

A few extra lines of code when raising the exceptions, yes, but that's versus the additional 17 lines of implementation and comments you're proposing, and I'd hardly describe it as "difficult" :)

> At GitHub, we rely heavily on the error codes returned from our SMS providers. We use this for analytics on provider outages, determining the correct message to show to the user, etc... It's pretty ugly to have to parse an error code out of an exception message with a regex.

Agreed, what I'm hinting at is would it make more sense to add more specific exceptions for those specific cases, similar to Nexmo::AuthenticationError?

**Pull request closed without merging**
