### PR TITLE
Handle encoding while sending messages

### PR DESCRIPTION
**Pull request by ghost**
- Detect when message contains multibytes characters to send the right value for type parameter
- Send the message charset in the Content-Type header to handle ISO-8889-1 messages

### CODE REVIEW

**Comment by timcraft** [comment]
@nicolas-ifg Thanks for this.

I think specifying the "type" parameter is the caller's responsibility, it's easy enough so I don't think setting that automatically makes sense.

Regardless of the encoding the text value will be percent encoded, which is all handled by Ruby, so shouldn't need to specify the charset on the Content-Type header, unless I'm missing something?

**Comment by ghost** [comment]
Thanks for reviewing this PR.

> I think specifying the "type" parameter is the caller's responsibility, it's easy enough so I don't think setting that automatically makes sense.

I think it's a great feature to make the component more easy to use. Anyway, the fact that the `type` is automatically set could be a setting itself: `autodetect_type: true` or something if you prefer giving the responsibility to the caller.

> Regardless of the encoding the text value will be percent encoded, which is all handled by Ruby, so shouldn't need to specify the charset on the Content-Type header, unless I'm missing something?

I found many use cases that were not properly handled by nexmo API when using non-unicode string. Specifying the charset in the request is required to send some latin1 characters for example.

Thank you for your time, I'm glad to help you on this topic.

**Comment by timcraft** [comment]
@nicolas-ifg Your help is appreciated, thanks! It would be great to make the gem easier to use, regardless of what language your messages are in.

I've just tested various combinations of encodings and parameters. It doesn't look like specifying the charset in the Content-Type header is necessary, even though that's probably the "correct" thing to do in theory. I can get cœur to show up correctly just by specifying `type: 'unicode'`, and that works both for utf-8 encoded strings and iso-8859-1 encoded strings. So if you specify the `type: 'unicode'` parameter, that should hopefully fix the problem in the short term?

I'll keep this open and consider making that default behaviour in the next major version. I think that would make it easier to use for anyone sending messages that aren't just ascii, and preferable to auto-detection (doesn't add much code/overhead and could still be overridden).

**Comment by ghost** [comment]
Hey @timcraft,

> I can get cœur to show up correctly just by specifying type: 'unicode', and that works both for utf-8 encoded strings and iso-8859-1 encoded strings. So if you specify the type: 'unicode' parameter, that should hopefully fix the problem in the short term?

The maximum SMS body length is actually 140 bytes, which equates to 160 GSM-encoded characters (7 bits each) or 70 unicode-encoded characters (2 bytes each).
So using `unicode` whatever the charset will generate extra cost for the users as Nexmo will send  70 characters long SMS even when the text can be encoded in single-byte coded charset.

The next step will be to help the user to optimize the type according the way the text can be encoded without loosing to much information.

See https://help.nexmo.com/hc/en-us/articles/204076866-How-Long-is-a-Single-SMS-body-

**Comment by timcraft** [comment]
@nicolas-ifg So no point making unicode the default I agree.

Handling every possible edge case and trying to prevent people from doing the wrong thing isn't maintainable. The default for the "type" parameter is "text". If you need to send characters not in the GSM character set, you can specify `type: 'unicode'`, or `type: 'binary'`, or whatever. Making sure you are sending the correct combination of these parameters is the caller's responsibility.

**Pull request closed without merging**
