### PR TITLE
Added support for Conversations API

### PR DESCRIPTION
**Pull request by hummusonrails**
## Description

This pull request adds support for the Conversations API into the Nexmo Ruby client library. 

The [Conversations API](https://developer.nexmo.com/api/conversation#overview) is currently in beta, but it is a stable beta and the request has been made to incorporate it in the client libraries.

The API supports the standard CRUD actions, such as:

* [Create A Conversation](https://developer.nexmo.com/api/conversation#createConversation)
* [List Conversations](https://developer.nexmo.com/api/conversation#listConversations)
* [Update A Conversation](https://developer.nexmo.com/api/conversation#replaceConversation)
* [Get A Specific Conversation](https://developer.nexmo.com/api/conversation#retrieveConversation)
* [Delete A Conversation](https://developer.nexmo.com/api/conversation#deleteConversation)

### CODE REVIEW

**Comment by hummusonrails** [comment]
Hey @timcraft ,

I could use your help in mocking a `conversation_id` in the new `conversations_test`. This is my first time adding more API support to our client library so I appreciate it! 🙏 

Have a great weekend!

Ben

**Review by timcraft — DISMISSED** [review]
Please can you make the following changes:

* Fix the formatting for consistency (2 spaces for indentation, and newlines at end of the files)

* Add a test for the Nexmo::Client#conversations method in test/nexmo/client_test.rb

**Comment by timcraft** [comment]
@benhayehudi Hey Ben. Thanks for making a start on it 👍

The `conversation_id` doesn't need to be mocked anywhere, it's just a static placeholder value.

It looks like the tests are failing because the `conversation_uri` method is referencing the calls endpoint instead of conversations—should be straightforward to fix.

I've added some review comments. I haven't checked it against the API docs—could you add a list of the endpoints/methods that still need to be added so we can see what's left to do?

**Comment by hummusonrails** [comment]
Thanks @timcraft! I appreciate you looking it over. Yes, let me revise the description with some more details on the required specs.

I'm getting an interesting error now for the `delete` method test: 

```
WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: DELETE ...
```

All the other tests are passing at this point.

**Comment by timcraft** [comment]
> I'm getting an interesting error now for the `delete` method test:

@benhayehudi You'll get that exception when the request the library is making doesn't match the one you've mocked. If you look at the difference between "You can stub this request with the following snippet" and "registered request stubs" you can see what isn't matching—in this case it's because you're specifying a Content-Type header and delete requests don't have one 😊

**Comment by hummusonrails** [comment]
> > I'm getting an interesting error now for the `delete` method test:
> 
> @benhayehudi You'll get that exception when the request the library is making doesn't match the one you've mocked. If you look at the difference between "You can stub this request with the following snippet" and "registered request stubs" you can see what isn't matching—in this case it's because you're specifying a Content-Type header and delete requests don't have one 😊

@timcraft - thank you so much for taking the time to explain, I really appreciate it!

**Comment by mheap** [comment]
Adding don't merge back to this as the conversation API is much bigger than just the covered methods. @judy2k could we get a list of requirements for user/members/events too?

**Comment by timcraft** [comment]
> the conversation API is much bigger than just the covered methods

Yep, that's what I meant by my earlier comment—suggest adding a [task list](https://help.github.com/articles/about-task-lists/) to the description as that gives us an visual summary of progress in the pull request list.

**Comment by hummusonrails** [comment]
Good morning wonderful people,

The details that @judy2k provided to open this task were the following:

> • 7 entities: Conversation, ConversationSummary, User, UserSummary, Member, MemberSummary & Event
> • 20 operations (functions/methods whatever). Mostly pretty straightforward CRUD operations with Application JWTs.

My approach was to build out each entity, one at a time. This is why this PR is labeled as "Added support for Conversations API". The next one was going to be similar, except "ConversationSummary," etc. until it was all done. I am taking the operations from the API documentation for each of those entities. I am happy to learn of a different approach to this, or if we want to integrate all 7 entities in one PR. I'm new to this and very glad to learn the best approach.

Thanks!

**Comment by timcraft** [comment]
> My approach was to build out each entity, one at a time.

In nexmo-ruby there's nothing special that needs to be done for entities, so it's just the different methods that need implementing. Seeing as it's all the same API and namespace I think it makes more sense as multiple commits in one pull request rather than separate pull requests. Feel free to fixup and squash down existing commits if that helps to structure things more logically.

**Comment by timcraft** [comment]
It would be good to get this in the next release.

@benhayehudi Are you still working on this? Or would you prefer if I finished it off?

**Comment by hummusonrails** [comment]
> It would be good to get this in the next release.
> 
> @benhayehudi Are you still working on this? Or would you prefer if I finished it off?

I agree! If you could wrap this one up, that would be excellent. Thank you Tim!

**Comment by timcraft** [comment]
@judy2k @mheap @benhayehudi This is ready for review. Can you have a look and let me know if you spot any issues? Then I can merge and ship in the next release.

**Review by hummusonrails — COMMENTED** [review]
This looks very good to me and this has been a good learning process personally as to how we integrate new APIs into our client libraries. Thanks for all the collaboration and work on this Tim!

**Pull request merged**
