### PR TITLE
[DEVX-2153] Pagination

### PR DESCRIPTION
**Pull request by hummusonrails**
DEVX-2153 Pagination

Introduce pagination auto-advance feature to the list actions in the relevant APIs, set it to `true` for all APIs except for listing all numbers action in the Numbers API.

### CODE REVIEW

**Comment by bencgreenberg** [comment]
@dragonmantank @fabianrbz This currently doesn't work for an API that doesn't return any indication in the response for page index, record index, total pages, links, etc. An example of that is the Numbers API. The list your numbers operation in the API provides no indication of any of those details.

Do we wish to maintain an `auto_advance` feature for APIs like that? If so, this will need to be refactored to make inclusion for those.

**Comment by hummusonrails** [comment]
@dragonmantank, as we discussed last night, this PR is ready for you to review it. I'd ask you to please try out the API calls for the list operation on various APIs using the SDK from this branch and make sure the results look accurate for your API account details. I've done so as well, but another set of eyes is crucial here.

**Review by dragonmantank — CHANGES_REQUESTED** [review]
It doesn't seem to be auto-advancing. If I specify a `page_size` parameter I only get back the first page.

```ruby
response = client.applications.list({page_size: 5})

response._embedded.applications.each do |application|
  puts "#{application.name}: #{application.id}"
end
```

**Comment by fabianrbz** [comment]
@bencgreenberg @dragonmantank I pushed a fix for it and added some specs.

**Review by dragonmantank — CHANGES_REQUESTED** [review]
That fixed my issue!

Overall this looks good, but the last question I have is is it possible to disable auto-advance when I know I don't want it enabled? For example, I'm in that small percentage of users that has hundreds of applications and I _want_ to manually page. I see we annotate `auto_advance` as an option, but it's hard-coded to true in the actual request call.

**Review by dragonmantank — CHANGES_REQUESTED** [review]
That fixed my issue!

Overall this looks good, but the last question I have is is it possible to disable auto-advance when I know I don't want it enabled? For example, I'm in that small percentage of users that has hundreds of applications and I _want_ to manually page. I see we annotate `auto_advance` as an option, but it's hard-coded to true in the actual request call.

**Comment by hummusonrails** [comment]
> That fixed my issue!
> 
> Overall this looks good, but the last question I have is is it possible to disable auto-advance when I know I don't want it enabled? For example, I'm in that small percentage of users that has hundreds of applications and I _want_ to manually page. I see we annotate `auto_advance` as an option, but it's hard-coded to true in the actual request call.

Yes, it is possible. You need to specify `auto_advance: false` in the method call, i.e if you want to restrict your page size to 5 and you don't want to auto-advance you would do the following:

```ruby
resp = client.applications.list(page_size: 5, auto_advance: false)
```

The hard-coded value in the request method functions as the default value for the parameter unless overruled by the actual invocation of the method.

**Review by dragonmantank — APPROVED** [review]
Looks good!

I was able to run the existing code snippets as they were with no issue, and manually passing things like `page_size` or `page` works, as does disabling the whole system

**Pull request merged**
